[options]
addons_path = /mnt/extra-addons
data_dir = /var/lib/odoo
admin_passwd = admin
db_host = db
db_port = 5432
db_user = odoowebsiteauth
db_password = odoowebsiteauth
db_name = odoowebsiteauth
list_db = False
